language: python
jobs:
  include:

    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode9.2
      language: shell
      before_install:
        - python --version
        - python -m pip install --upgrade pip
        - sudo pip install -e . --pre
        - python -m pip install hapiplot --upgrade
        - sudo pip install tox-travis



install: pip install --upgrade pip
script:
  - tox -e repo-test
