language: python
jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.6
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python3 -m pip install tox-travis

    - name: "Python 3.7 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.7
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python3 -m pip install tox-travis

    - name: "Python 3.8 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.8
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python3 -m pip install tox-travis

    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode9.3
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - sudo pip install tox-travis




install: pip install --upgrade pip
script:
  - tox -e repo-test
