language: python
jobs:
  include:

    - name: "Python 3.6 on macOS"
      os: osx
      osx_image: xcode9.4
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - sudo pip3 install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - sudo pip3 install tox-travis



install: pip install --upgrade pip
script:
  - tox -e repo-test
