language: python
jobs:
  include:

    - name: "Python 3.6 on Windows"
      os: windows
      language: shell
      before_install:
        - choco install python --version 3.6.5
        - python --version
        - python -m pip install --upgrade pip
        - sudo pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - python -m pip install tox-travis
      env: PATH=/c/Python36:/c/Python36/Scripts:$PATH



install: pip install --upgrade pip
script:
  - tox -e repo-test
