language: python
jobs:
  include:
    - name: "Python 3.6 on Linux"
      os: linux
      dist: xenial
      language: python
      python: 3.6
      before_install:
        - sudo rm /usr/bin/python
        - sudo ln -s /usr/bin/python3 /usr/bin/python
        - python3 --version
        - python3 -m pip install tox-travis

install: pip install --upgrade pip
script:
  - tox -e repo-test
