language: python
jobs:
  include:

    - name: "Python 3.6 on macOS"
      os: osx
      python: "3.6"
      osx_image: xcode10
      language: shell
      before_install:
        - python3 --version
        - python3 -m pip install --upgrade pip
        - sudo pip install -e . --pre
        - python3 -m pip install hapiplot --upgrade
        - sudo pip install tox-travis



install: pip install --upgrade pip
script:
  - tox -e repo-test
